name: variable substitution

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: microsoft/variable-substitution@v1 
      with:
        files: '**/google-services.json'
      env:
        client.api_key.current_key: "<api-key>"
